name:                sese-scripts
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/prikhi/sese-scripts#readme
license:             BSD3
author:              Pavan Rikhi
maintainer:          pavan.rikhi@gmail.com
copyright:           GPL-3.0
category:            Web
extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - cassava
  - persistent
  - text

library:
  source-dirs:        src
  dependencies:
    - bytestring
    - monad-logger
    - persistent-mysql
    - persistent-template
    - transformers

executables:
  export-descriptions:
    source-dirs:      exe
    main:             ExportDescriptions.hs
    other-modules:    []
    dependencies:
      - sese-scripts
  export-pages:
    source-dirs:      exe
    main:             ExportPages.hs
    other-modules:    []
    dependencies:
      - sese-scripts
  export-price-status:
    source-dirs:      exe
    main:             ExportPriceStatus.hs
    other-modules:    []
    dependencies:
      - sese-scripts
  import-price-status:
    source-dirs:      exe
    main:             ImportPriceStatus.hs
    other-modules:    []
    dependencies:
      - sese-scripts
      - bytestring
      - vector
